In [19]:
import torch

In [20]:
real_images = torch.randn(64,3,224,224)
eta = torch.FloatTensor(real_images.shape[0],1,1,1).uniform_(0,1).expand(real_images.shape)
eta

tensor([[[[0.5323, 0.5323, 0.5323,  ..., 0.5323, 0.5323, 0.5323],
          [0.5323, 0.5323, 0.5323,  ..., 0.5323, 0.5323, 0.5323],
          [0.5323, 0.5323, 0.5323,  ..., 0.5323, 0.5323, 0.5323],
          ...,
          [0.5323, 0.5323, 0.5323,  ..., 0.5323, 0.5323, 0.5323],
          [0.5323, 0.5323, 0.5323,  ..., 0.5323, 0.5323, 0.5323],
          [0.5323, 0.5323, 0.5323,  ..., 0.5323, 0.5323, 0.5323]],

         [[0.5323, 0.5323, 0.5323,  ..., 0.5323, 0.5323, 0.5323],
          [0.5323, 0.5323, 0.5323,  ..., 0.5323, 0.5323, 0.5323],
          [0.5323, 0.5323, 0.5323,  ..., 0.5323, 0.5323, 0.5323],
          ...,
          [0.5323, 0.5323, 0.5323,  ..., 0.5323, 0.5323, 0.5323],
          [0.5323, 0.5323, 0.5323,  ..., 0.5323, 0.5323, 0.5323],
          [0.5323, 0.5323, 0.5323,  ..., 0.5323, 0.5323, 0.5323]],

         [[0.5323, 0.5323, 0.5323,  ..., 0.5323, 0.5323, 0.5323],
          [0.5323, 0.5323, 0.5323,  ..., 0.5323, 0.5323, 0.5323],
          [0.5323, 0.5323, 0.5323,  ..., 0

In [1]:
from distutils.sysconfig import get_python_lib
print(get_python_lib())

/opt/conda/envs/cmu16824hw2/lib/python3.8/site-packages


In [3]:
import torch

In [1]:
import os

In [2]:
os.environ.get('PYTORCH_JIT', 1)

1

In [2]:
vals = torch.linspace(-1, 1, steps=10)
print(vals)

tensor([-1.0000, -0.7778, -0.5556, -0.3333, -0.1111,  0.1111,  0.3333,  0.5556,
         0.7778,  1.0000])


In [3]:
x, y = torch.meshgrid(vals, vals)
x, y = x.flatten(), y.flatten()
comb = torch.vstack([x,y]).T
comb.shape

/home/ubuntu/anaconda3/envs/cmu16824hw2/lib/python3.8/site-packages/torch/functional.py:513: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3609.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]


torch.Size([100, 2])

In [4]:
z = torch.zeros(100, 128)
z[:,0], z[:,1] = x, y
print(z[:,0:2])

tensor([[-1.0000, -1.0000],
        [-1.0000, -0.7778],
        [-1.0000, -0.5556],
        [-1.0000, -0.3333],
        [-1.0000, -0.1111],
        [-1.0000,  0.1111],
        [-1.0000,  0.3333],
        [-1.0000,  0.5556],
        [-1.0000,  0.7778],
        [-1.0000,  1.0000],
        [-0.7778, -1.0000],
        [-0.7778, -0.7778],
        [-0.7778, -0.5556],
        [-0.7778, -0.3333],
        [-0.7778, -0.1111],
        [-0.7778,  0.1111],
        [-0.7778,  0.3333],
        [-0.7778,  0.5556],
        [-0.7778,  0.7778],
        [-0.7778,  1.0000],
        [-0.5556, -1.0000],
        [-0.5556, -0.7778],
        [-0.5556, -0.5556],
        [-0.5556, -0.3333],
        [-0.5556, -0.1111],
        [-0.5556,  0.1111],
        [-0.5556,  0.3333],
        [-0.5556,  0.5556],
        [-0.5556,  0.7778],
        [-0.5556,  1.0000],
        [-0.3333, -1.0000],
        [-0.3333, -0.7778],
        [-0.3333, -0.5556],
        [-0.3333, -0.3333],
        [-0.3333, -0.1111],
        [-0.3333,  0